# Generated by Django 4.2.9 on 2024-01-03 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_menu_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='phone_number',
            new_name='number_of_guests',
        ),
    ]
